# Generated by Django 5.2.7 on 2025-10-13 02:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_patientform_uploaded_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=20)),
                ('new_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True, help_text='Optional reason for the status change', null=True)),
                ('changed_by', models.ForeignKey(help_text='User who made the status change', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('patient_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_changes', to='dashboard.patientform')),
            ],
            options={
                'verbose_name': 'Status Change Log',
                'verbose_name_plural': 'Status Change Logs',
                'ordering': ['-changed_at'],
            },
        ),
    ]
