# Generated by Django 5.2.7 on 2025-10-13 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_statuschangelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='statuschangelog',
            name='viewed_by_admin',
            field=models.BooleanField(default=False, help_text='Whether admin has seen this change'),
        ),
    ]
