# Generated by Django 5.2.7 on 2025-10-10 16:13

import dashboard.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(blank=True, help_text='Will be extracted from form if not provided', max_length=255, null=True)),
                ('uploaded_file', models.FileField(help_text='Supported: PDF, PNG, JPG (Max 10MB)', upload_to=dashboard.models.upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'jpeg'])])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('ai_feedback', models.TextField(blank=True, null=True)),
                ('extracted_patient_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
