# Generated by Django 5.2.7 on 2025-10-10 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientform',
            name='ai_decision',
            field=models.CharField(choices=[('analyzing', 'Analyzing...'), ('accept', 'Accept'), ('reject', 'Reject'), ('review_required', 'Review Required')], default='analyzing', max_length=20),
        ),
        migrations.AddField(
            model_name='patientform',
            name='processing_time_seconds',
            field=models.IntegerField(blank=True, help_text='Processing time in seconds', null=True),
        ),
        migrations.AddField(
            model_name='patientform',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
