# Generated by Django 5.2.7 on 2025-10-13 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_statuschangelog_viewed_by_admin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StatusChangeLog',
        ),
    ]
