# Generated by Django 5.2.7 on 2025-11-07 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_add_previous_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientform',
            name='previous_status',
        ),
    ]
