# Generated by Django 5.2.7 on 2025-11-07 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_conversation_patient_form'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='patient_form',
        ),
    ]
